# -*- coding: utf-8 -*-
"""Blur.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o2NmIoGUxIgl9mDBivxKzc3sxBHzWjjX
"""

import cv2
from google.colab.patches import cv2_imshow
import os

os.makedirs('/content/image')
os.makedirs('/content/mask')

img = cv2.imread('/content/image/Cars9.png')
mask = cv2.imread('/content/mask/Cars9.png',0)
# mask_inv=cv2.bitwise_not(mask)
res = cv2.bitwise_or(img,img,mask=mask)
img_without_number=img-res

image = cv2.imread('/content/image/Cars9.png')
image = cv2.GaussianBlur(image, (15, 15), 0)
image = cv2.GaussianBlur(image, (15, 15), 0)

blurred_img = cv2.GaussianBlur(image, (15, 15), 0)
mask = mask

res2=cv2.bitwise_or(blurred_img,blurred_img,mask=mask)

cv2_imshow(img_without_number+res2)